parameters:
#    cms_email_notification.example.class: Acme\CacheManagementBundle\Example

services:
#    cms_email_notification.example:
#        class: %cms_email_notification.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
