security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_MEINEKE: ROLE_MEINEKE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        wsse_secured:
            pattern: ^/api/secured/.*
            stateless: true
            wsse: true