Acme\DataBundle\Entity\StoresPhotos:
    type: entity
    table: stores_photos
    repositoryClass: Acme\DataBundle\Entity\Repository\StoresPhotosRepository 
    indexes:
        fk_stores_photos_stores1_idx:
            columns:
                - stores_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        orderIdx:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
        dateUpdated:
            type: datetime
            nullable: true
            comment: ''
            column: date_updated
        dateCreated:
            type: datetime
            nullable: true
            comment: ''
            column: date_created
    manyToOne:
        stores:
            targetEntity: Stores
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                stores_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
