Acme\DataBundle\Entity\UsCities:
    type: entity
    table: us_cities
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        zip:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
        city:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        citySlug:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        state:
            type: string
            nullable: true
            length: 2
            fixed: false
            comment: ''
        lat:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        lng:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
