parameters:
#    acme_data.example.class: Acme\DataBundle\Example

services:
#    acme_data.example:
#        class: %acme_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
