<?php

namespace Acme\DataBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppointmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentsRepository extends EntityRepository {

  public function getFutureAppointments($userId) {

    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('appointments.id AS id, appointments.appointmentDate AS appointmentDate, appointments.vehicleMake AS vehicleMake, appointments.vehicleModel AS vehicleModel, stores.storeId AS storeId, stores.streetAddress1 AS streetAddress1, stores.streetAddress2 AS streetAddress2, stores.locationCity AS locationCity, stores.locationState AS locationState, stores.locationPostalCode AS locationPostalCode, stores.phone AS phone, stores.rawPhone AS rawPhone, stores.semCamPhone AS semCamPhone, stores.rawSemCamPhone AS rawSemCamPhone');
    $qb->from('AcmeDataBundle:Appointments', 'appointments');
    $qb->leftJoin('AcmeDataBundle:Stores', 'stores', 'WITH', 'stores.id = appointments.stores');
    $qb->where('appointments.users = :userId');
    $qb->andWhere('appointments.appointmentDate > :today');
    $qb->setParameter('userId', $userId);
    $qb->setParameter('today', date("Y-m-d H:i:s"));
    $qb->orderBy('appointments.appointmentDate', 'DESC');

    return $qb->getQuery()->getArrayResult();
  }

}
