<?php

namespace Acme\DataBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RewardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardsRepository extends EntityRepository {

  public function getMyRewards($myPoints) {

    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('rewards.id AS id, rewards.name AS name, rewards.points AS points, rewards.image AS image');
    $qb->from('AcmeDataBundle:Rewards', 'rewards');
    $qb->where('rewards.points <= :myPoints');
    $qb->setParameter('myPoints', $myPoints);
    $qb->orderBy('rewards.points', 'DESC');

    return $qb->getQuery()->getArrayResult();
  }

}
