<?php

namespace Acme\DataBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesRepository extends EntityRepository {

	public function getPopularServices() {

		$qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('services.title AS title, services.slug AS slug, services.icon AS icon, services.headerServiceText AS headerServiceText, services.shortDescription AS shortDescription, services.longDescription AS longDescription');
    $qb->from('AcmeDataBundle:Services', 'services');
    $qb->where('services.isMain = 1');
    $qb->orderBy('services.orderIdx', 'ASC');

    return $qb->getQuery()->getArrayResult();

	}

  public function getCMSServices() {

    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('services.id AS id, services.title AS title');
    $qb->from('AcmeDataBundle:Services', 'services');
    $qb->where('services.isMain = 1');
    $qb->orWhere('(services.isMain = 0');
    $qb->andWhere('services.isPrimary = 1)');
    $qb->orWhere('(services.isMain = 0');
    $qb->andWhere('services.isAdditional = 1)');
    $qb->orderBy('services.title', 'ASC');

    return $qb->getQuery()->getArrayResult();

  }

  public function getService($slug) {

    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('services.title AS title, services.slug AS slug, services.icon AS icon, services.headerServiceText AS headerServiceText, services.shortDescription AS shortDescription, services.longDescription AS longDescription');
    $qb->from('AcmeDataBundle:Services', 'services');
    $qb->where('services.slug = :slug');
    $qb->setParameter('slug', $slug);

    return $qb->getQuery()->getArrayResult();

  }

}
