<?php

namespace Acme\DataBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SlidesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlidesRepository extends EntityRepository {

	public function getSlides($storeId = "") {

		$qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('slides');
    $qb->from('AcmeDataBundle:Slides', 'slides');

    if($storeId) {
      $qb->where('slides.stores = :storeId');
      $qb->setParameter('storeId', $storeId);
    }
    else {
      $qb->where('slides.stores IS NULL');
    }
    $qb->orderBy('slides.id', 'ASC');

    return $qb->getQuery()->getArrayResult();

	}

}
