<?php

namespace Acme\DataBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StoresServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoresServicesRepository extends EntityRepository {

  public function getStoreServices($id) {

    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('services');
    $qb->from('AcmeDataBundle:StoresHasServices', 'storesHasServices');
    $qb->leftJoin('AcmeDataBundle:Services', 'services', 'WITH', 'services.id = storesHasServices.services');
    $qb->where('storesHasServices.stores = :id');
    $qb->andWhere('services.isCsv = 1');
    $qb->setParameter('id', $id);
    $qb->orderBy('services.orderIdx', 'ASC');

    return $qb->getQuery()->getResult();

  }

}
