<?php

namespace Acme\DataBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StoresPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoresPhotosRepository extends EntityRepository {

  public function getStorePhotos($id) {

    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('storesPhotos.name AS name');
    $qb->from('AcmeDataBundle:StoresPhotos', 'storesPhotos');
    $qb->where('storesPhotos.stores = :id');
    $qb->setParameter('id', $id);
    $qb->orderBy('storesPhotos.orderIdx', 'ASC');

    return $qb->getQuery()->getArrayResult();

  }

}
