<?php

namespace Acme\DataBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TermsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermsRepository extends EntityRepository {

  public function getTerms($keyword = '', $firstLetter = '', $exactKeyword = '') {
    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('terms.id AS id, terms.term AS title, terms.description AS description');
    $qb->from('AcmeDataBundle:Terms', 'terms');

    if($firstLetter) {
      $qb->where('terms.term LIKE :firstLetter');
      $qb->setParameter('firstLetter', $firstLetter . '%');
    }
    else if($keyword) {
      $qb->where('terms.term LIKE :keyword');
      $qb->setParameter('keyword', '%' . $keyword . '%');
    } else if($exactKeyword) {
      $qb->where('terms.term = :exactKeyword');
      $qb->setParameter('exactKeyword', $exactKeyword);
    }

    return $qb->getQuery()->getArrayResult();

  }

	public function getTermBySlug($slug) {
  	$qb = $this->getEntityManager()->createQueryBuilder();
  	$qb->select('terms.id AS id, terms.term AS title, terms.description AS description');
  	$qb->from('AcmeDataBundle:Terms', 'terms');
    $qb->where('terms.slug = :slug');
    $qb->setParameter('slug', $slug);

    return $qb->getQuery()->getArrayResult();

	}

  public function getRandomTerm() {

    $conn = $this->getEntityManager()->getConnection(); //create a connection with your DB

    $sql = "SELECT terms.id AS id, terms.term AS title, terms.description AS description FROM terms ORDER BY RAND() LIMIT 1"; //your SQL Query

    $stmt = $conn->prepare($sql); //prepare your sql
    $stmt->execute(); //execute your sql
    $result = $stmt->fetchAll(); //fetch your result

    return $result;

	}

}
