<?php

namespace Acme\DataBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

use Acme\DataBundle\Model\Constants\UsersRole;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository {

  public function getUser($id) {

    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('users.id AS id, users.firstName AS firstName, users.lastName AS lastName, users.email AS email, companies.id AS companyId, companies.companyName AS company, users.companyPosition AS companyPosition, users.organization AS organization, countries.id AS countryId, countries.countryName AS countryName, users.state AS state, users.roles AS role, users.status AS status');
    $qb->from('AcmeDataBundle:Users', 'users');
    $qb->where('users.id = :id');
    $qb->setParameter('id', $id);

    return $qb->getQuery()->getArrayResult();

  }

}
